[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmd = 'cd backend && npm install'

[phases.build]
cmd = 'cd backend && npx prisma generate'

[phases.start]
cmd = 'cd backend && npm start'

[variables]
NODE_ENV = 'production'
